SourceCode/Management-Distributor/Management-Distributor/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Xml.Linq;
using Distributor.Dao._DbContext;
using Distributor.POCO;
using Distributor.Service.Interfaces;
using Management_Distributor.ExceptionHandler;
using Management_Distributor.Service.Interfaces;
using System.Windows;
using Microsoft.Ajax.Utilities;
using System.Web.Helpers;

namespace Management_Distributor.Controllers
{
    [Authorize(Roles ="staff")]
    public class OrdersController : Controller
    {

        private IProductService productService = null;
        private IOrderService orderService = null;
        private IOrderDetailService detailService  = null;
        //private IPaymentService paymentService = null;
        private IInvoiceService invoiceService = null;
        private IDistributorService distributorService = null;
        private IEmployeeService employeeService = null;

        public OrdersController(IProductService _productService, IOrderService _orderService, IOrderDetailService _detailService, IInvoiceService _invoiceService, IDistributorService _distributorService, IEmployeeService _employeeService)
        {
            this.productService = _productService;
            this.orderService = _orderService;
            this.detailService = _detailService;
            this.invoiceService = _invoiceService;
            this.distributorService = _distributorService;
            this.employeeService = _employeeService;

            //this.paymentService = _paymentService;
        }

        protected override void HandleUnknownAction(string actionName)
        {
            try
            {
                this.View(actionName).ExecuteResult(this.ControllerContext);
            }
            catch (Exception ex)
            {
                //ExceptionProofer.LogToFile()
                Response.Redirect("PageNotFound");
            }
        }
        

        public ActionResult Details(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = orderService.FindById(Convert.ToInt32(id));
            if (order == null)
            {
                return HttpNotFound();
                //throw new HttpException(404, "Some description");
            }
            else
            {
                _Distributor distributor = distributorService.GetOne(order.DistributorId);
                Employee employee = employeeService.GetOne(order.EmployeeId);
                ViewBag.EmpInfoName = employee.EmpName;
                ViewBag.EmpInfoId = employee.EmployeeId;
               List <OrderDetail> detail = detailService.FindByOrderId(order.OrderId);
                Invoice invoice = invoiceService.FindByOrderId(order.OrderId);

                return View(Tuple.Create(distributor, order, detail));

            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Order order = orderService.FindById(id);
            if (order != null)
            {
                // only allowed to change order-detail if its invoice haven't been created yet
                if (invoiceService.FindByOrderId(order.OrderId) != null)
                {
                    ViewBag.sign = 1;
                    return View();
                }
                else
                {
                    ViewBag.OrderID = order.OrderId;
                    ViewBag.OrderDetail = detailService.FindByOrderId(id);
                    return View(productService.GetAll().ToList());
                }
               
            }
            else {
                ViewBag.sign = -1;
                return View();
            }
            
        }

        [HttpPost]
        public JsonResult SerializeFormDataForEdit(int OrderID, FormCollection _collection)
        {
            Order order = orderService.FindById(OrderID);
            if (order == null)
                return Json(new { Success = false, Message = "This OrderID not found" }, JsonRequestBehavior.AllowGet);
            if (_collection != null)
            {
                string[] _productID, _DemandQty, _ActualQty, _price, _amt, _flag, _detailId;
                //for orderDetails
                _productID = _collection["ProductID"].Split(',');
                _DemandQty = _collection["DemandQty"].Split(',');
                _ActualQty = _collection["ActualQty"].Split(',');
                _price = _collection["Price"].Split(',');
                _amt = _collection["Amount"].Split(',');
                _flag = _collection["Flag"].Split(',');
                _detailId = _collection["DetailId"].Split(',');
                //for order
                DateTime requireDate = Convert.ToDateTime(_collection["RequireDate"]);
               
                decimal _total = Convert.ToDecimal(_collection["Total"]);
                int DistributorID = Convert.ToInt32(_collection["DistributorID"]);
                //decimal _discount = Convert.ToDecimal(_collection["Discount"]);
                //decimal _grandTotal = Convert.ToDecimal(_collection["GrandTotal"]);
                DateTime _date = DateTime.Now;

                order.RequireDeliveryDate = requireDate;
                order.ToTalAmount = _total;
                order.EmployeeId = Convert.ToInt32(Session["EmployeeId"]);
                //order.Update_At = DateTime.Now;
                int success = 0;
                //success = orderService.Edit(order);

                if (success > 0)
                {
                    //service.UpdateStock(_stockID, _qty);
                    if ((detailService.AddOrEditListDetail(order.OrderId, _detailId, _productID, _price, _DemandQty, _ActualQty,_flag)) == _productID.Count())
                    {
                        //Invoice invoice = new Invoice()
                        //{
                        //    OrderId = orderID,
                        //    Amount = _total,
                        //    EmployeeId = Convert.ToInt32(Session["EmployeeId"])
                        //};
                        return Json(new { success = true, message = "Order added" }, JsonRequestBehavior.AllowGet);
                    }

                    return Json(new { success = false, message = "wrong with insert detail" }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { success = false, message = "wrong with generic Order" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, message = "wrong from form" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {

            //List<_Distributor> distributors = distributorService.GetAll();
            //ViewBag.DistributorId = new SelectList(distributors, "DistributorId", "DistributorName");
            return View(productService.GetAll().ToList());
        }
        

        [HttpPost]
        public JsonResult SerializeFormData(FormCollection _collection)
        {
            if (_collection != null)
            {
                string[] _productID, _DemandQty, _ActualQty, _price, _amt;
                //for orderDetails
                _productID = _collection["ProductID"].Split(',');
                _DemandQty = _collection["DemandQty"].Split(',');
                _ActualQty = _collection["ActualQty"].Split(',');
                _price = _collection["Price"].Split(',');
                _amt = _collection["Amount"].Split(',');
 
                //for order
                DateTime requireDate = Convert.ToDateTime(_collection["RequireDate"]);
                decimal _total = Convert.ToDecimal(_collection["Total"]);
                int DistributorID = Convert.ToInt32(_collection["DistributorID"]);
                //decimal _discount = Convert.ToDecimal(_collection["Discount"]);
                //decimal _grandTotal = Convert.ToDecimal(_collection["GrandTotal"]);
                DateTime _date = DateTime.Now;

                Order order = new Order()
                {
                    OrderDate = _date,
                    ToTalAmount = _total,
                    DistributorId = DistributorID,
                    //Discount = _discount,
                    //GrandTotal = _grandTotal,
                    //Tax = 0,
                    //UserID = User.Identity.GetUserId(),
                    EmployeeId = Convert.ToInt32(Session["EmployeeId"]),
                    RequireDeliveryDate = requireDate
                    //Remarks = "-"
                };



                int orderID = orderService.Add(order);

                if (orderID > 0)
                {
                    //service.UpdateStock(_stockID, _qty);
                    if ((detailService.AddListDetail(orderID, _productID, _price, _DemandQty, _ActualQty)) == _productID.Count())
                    {
                        Invoice invoice = new Invoice()
                        {
                            OrderId = orderID,
                            Amount = _total,
                            EmployeeId = Convert.ToInt32(Session["EmployeeId"])
                        };
                        return Json(new { success = true, message = "Order added" }, JsonRequestBehavior.AllowGet);
                    }
                        
                    return Json(new { success = false, message = "wrong with insert detail" }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { success = false, message = "wrong with generic Order" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, message = "wrong from form" }, JsonRequestBehavior.AllowGet);
        }



        //public JsonResult GetAllJSON()
        //{

        //}

SourceCode/Management-Distributor/Management-Distributor/Controllers/RegionsController.cs
using Distributor.POCO;
using Management_Distributor.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Management_Distributor.Controllers
{
    [Authorize(Roles = "staff")]
    public class RegionsController : Controller
    {
        private IRegionService regionService = null;

        public RegionsController(IRegionService regionService)
        {
            this.regionService = regionService;
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                return View(new Region());
            }
            else
            {
                Region Region = regionService.GetOne(id);
                return View(Region);
            }

        }

        [HttpPost]
        public ActionResult AddOrEdit(Region Region)
        {
            if (Region.RegionId == 0)
            {
                if (regionService.Add(Region))
                {
                    return Json(new { success = true, message = "Add successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = "Failed to add" }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {

                if (regionService.Edit(Region))
                {
                    return Json(new { success = true, message = "Edit successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = "Failed to edit" }, JsonRequestBehavior.AllowGet);
                }

            }
        }

        public ActionResult Index()
        {
            return View();

        }

        public JsonResult LoadData()
        {
            //var data = db.Categories.ToList();
            var data = regionService.GetAll();
            return Json(new { data }, JsonRequestBehavior.AllowGet);
        }

        // GET: Categories/Details/5
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region Region = regionService.GetOne(id);
            if (Region == null)
            {
                return HttpNotFound();
            }
            return View(Region);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RegionId,RegionName,Description")] Region Region)
        {
            if (ModelState.IsValid)
            {
                regionService.Add(Region);
                return RedirectToAction("Index");
            }

            return View(Region);
        }

        // GET: Categories/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    if (id == 0)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Region Region = regionService.GetOne(id);
        //    if (Region == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(Region);
        //}

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RegionId,RegionName,Description")] Region Region)
        {
            if (ModelState.IsValid)
            {
                regionService.Edit(Region);
                return RedirectToAction("Index");
            }
            return View(Region);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Region Region = regionService.GetOne(id);
            if (Region == null)
            {
                return HttpNotFound();
            }
            return View(Region);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Region Region = regionService.GetOne(id);
            regionService.Delete(Region);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Remove(int id)
        {
            Region Region = regionService.GetOne(id);
            regionService.Delete(Region);
            return Json(new { success = true, message = "Removal success!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

SourceCode/Management-Distributor/Management-Distributor/Views/Shared/_AdminLteBreadcrumb.cshtml
@* 
 This breadcrumb partial is meant to be dropped into the top of the main content page
    and uses the AdminLte.Breadcrumb class to dynamically build the breadcrumb per page
*@

@if (ViewBag.Breadcrumb != null)
{
    <ol class="breadcrumb">
        @foreach (Crumb crumb in ViewBag.Breadcrumb)
        {
            <li>
                @if (crumb.HasLink)
                {
                    <a href="@crumb.Link">
                        @if (crumb.HasIcon)
                        {
                            <i class="fa @crumb.Icon"></i>
                        }

                        <span>@crumb.Text</span>
                    </a>
                }
                else
                {
                    if (crumb.HasIcon)
                    {
                        <i class="fa @crumb.Icon"></i>
                    }

                    <span>@crumb.Text</span>
                }
            </li>
        }
    </ol>
}

SourceCode/Management-Distributor/Management-Distributor/Views/Shared/_AdminLteLayout.cshtml
@* 
 This is the main dashboard layout that creates the AdminLTE look and feel
    It includes all of the relevant CSS and Js in this project and across CDNs around the web for optimal load times
    TODO: Use this layout in your views by either setting the "Layout" property 
    or changing your  _ViewStart.cshtml to use this layout
 *@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*TODO: Change App name*@
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    @*Source Sans Pro from Google Fonts*@
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic" rel="stylesheet" />
    @*Bundle CSS, assuming includes Bootstrap CSS *@
    @Styles.Render("~/Content/css")
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="~/Scripts/AdminLTE/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="~/Scripts/AdminLTE/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="~/Content/AdminLTE/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    @*TODO: AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load.*@
    <link href="~/Content/AdminLTE/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="skin-blue">

    <div class="wrapper">

        @Html.Partial("_AdminLteTopMenu")
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_AdminLteLeftMenu")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.TitleSmall</small>
                </h1>
                @Html.Partial("_AdminLteBreadcrumb")
            </section>
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.0
            </div>
            <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
        </footer>
    </div><!-- ./wrapper -->
    @* Bundles assume jquery 2.1.3 and Bootstrap 3 *@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- FastClick -->
    <script src='~/Scripts/AdminLTE/plugins/fastclick/fastclick.min.js'></script>
    <!-- AdminLTE App -->
    <script src="~/Scripts/AdminLTE/app.js" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="~/Scripts/AdminLTE/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="~/Scripts/AdminLTE/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="~/Scripts/AdminLTE/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="~/Scripts/AdminLTE/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="~/Scripts/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- ChartJS 1.0.1 -->
    <script src="~/Scripts/AdminLTE/plugins/chartjs/Chart.min.js" type="text/javascript"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

SourceCode/Management-Distributor/Management-Distributor/Views/Shared/_Layout.cshtml
@using Distributor.ViewModels
@{
    ViewBag.Title = "Home Page";
    var user = @Session["user"] as SessionStorageModel;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <meta name="description" content="">'
    <link rel="shortcut icon" href="~/Assets/Images/aps.net.ico">

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="~/Content/bootstrap-v4.0.0-beta.2.min.css">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />


    @*<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />*@
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery.dataTables-1.10.16.css" rel="stylesheet" />
    <!-- Font Awesome CSS-->
    @*<link href="~/Content/DataTables/css/dataTables.bootstrap.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="~/Content/fontastic.css">
    <!-- Google fonts - Poppins -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/Content/bootstrap-4-material-admin.style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/Content/custom.css">
    <link href="~/Content/table-custom.css" rel="stylesheet" />

    <link href="~/Content/AdminLTE/AdminLTE.css" rel="stylesheet" />
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/favicon.ico">

    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/notify.js"></script>
    <script src="~/Scripts/umd/popper.min.js"> </script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap-v4.0.0-beta.2.min.js"></script>
    <script src="~/Scripts/sweetalert.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/jquery-v1.4.1.cookie.js"> </script>
    <script src="~/Scripts/Chart-2.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate-v1.17.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <link href="~/Content/sweetalert/sweet-alert.css" rel="stylesheet" />

    <style>
        .main-footer {
            margin-left: 0;
        }
    </style>
    @*@{
            var EmployeeName = (string)Session["EmployeeName"];
        }*@

</head>
<body>
    <div class="page">
        <!-- Main Navbar-->
        <header class="header">
            <nav class="navbar navbar-fixed-top">
                <!-- Search Box-->
                <div class="search-box">
                    <button class="dismiss"><i class="icon-close"></i></button>
                    <form id="searchForm" action="#" role="search">
                        <input type="search" placeholder="What are you looking for..." class="form-control">
                    </form>
                </div>
                <div class="container-fluid">
                    <div class="navbar-holder d-flex align-items-center justify-content-between">
                        <!-- Navbar Header-->
                        <div class="navbar-header">
                            <!-- Navbar Brand --><a href="index.html" class="navbar-brand">
                                <div class="brand-text brand-big"><span>Bootstrap</span><strong>Dashboard</strong></div>
                                <div class="brand-text brand-small"><strong>BD</strong></div>
                            </a>
                            <!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
                        </div>
                        <!-- Navbar Menu -->
                        <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                            <!-- Search-->
                            <li class="nav-item d-flex align-items-center"><a id="search" href="#"><i class="icon-search"></i></a></li>
                            <!-- Logout    -->
                            <li class="nav-item">

                                <a href="@Url.Action("Logout", "Account")" class="nav-link logout">
                                    Logout
                                    <i class="fa fa-sign-out"></i>
                                </a>

                                @*@Html.ActionLink("LogOut", "Logout", "Account", null, new { @class = "nav-link logout" })
                                    <a href="login.html" class="nav-link logout">Logout
                                        <i class="fa fa-sign-out"></i>
                                    </a>*@
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="page-content d-flex align-items-stretch">
            <!-- Side Navbar -->
            <nav class="side-navbar">
                <!-- Sidebar Header-->
                <div class="sidebar-header d-flex align-items-center">
                    <div class="avatar"><img src="@user.Avatar" alt="..." class="img-fluid rounded-circle"></div>
                    <div class="title">
                        <h1 class="h4">@user.Name</h1>
                    </div>
                </div>
                <!-- Sidebar Navidation Menus-->
                <ul class="list-unstyled">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a href="@Url.Action("Index", "Departments")">
                                    <i class="fa fa-users"></i>
                                    Departments
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Employees")">
                                    <i class="fa fa-user"></i>
                                    Employees
                                </a>
                            </li>
                        }
                    }

                    <li>
                        <a href="@Url.Action("Index", "Categories")">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                            Categories
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Page", "Products")">
                            <i class="fa fa-gift" aria-hidden="true"></i>
                            Products
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Create", "Orders")">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                            Create Order
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Regions")">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                            Region
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "_Distributors")">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                            Distributor
                        </a>
                    </li>

                    @*<li class="active"><a href="index.html"> <i class="icon-home"></i>Home </a></li>*@
                    <li><a href="tables.html"> <i class="icon-grid"></i>Tables </a></li>
                    <li><a href="charts.html"> <i class="fa fa-bar-chart"></i>Charts </a></li>
                    <li><a href="forms.html"> <i class="icon-padnote"></i>Forms </a></li>
                    <li>
                        <a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-interface-windows"></i>Example dropdown </a>
                        <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                            <li><a href="#">Page</a></li>
                            <li><a href="#">Page</a></li>
                            <li><a href="#">Page</a></li>
                        </ul>
                    </li>
                </ul><span class="heading">Extras</span>
                <ul class="list-unstyled">
                    <li> <a href="#"> <i class="icon-flask"></i>Demo </a></li>
                    <li> <a href="#"> <i class="icon-screen"></i>Demo </a></li>
                    <li> <a href="#"> <i class="icon-mail"></i>Demo </a></li>
                    <li> <a href="#"> <i class="icon-picture"></i>Demo </a></li>
                </ul>
            </nav>
            <!-- Main Content Area -->
            <div class="content-inner">
                @RenderBody()
                <!-- Page Footer-->
                @*<footer style="width:100%" class="main-footer">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-6">
                                    <p>Awakening &copy; 2017-2019</p>
                                </div>
                                <div class="col-sm-6 text-right">
                                    <p>Design by <a href="https://bootstrapious.com/admin-templates" class="external">Bootstrapious</a></p>

                                </div>
                            </div>
                        </div>
                    </footer>*@
            </div>

        </div>
    </div>



    <!-- Javascript files-->
    <!-- Main File-->
    <script src="~/Scripts/front.js"></script>


    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@

    @RenderSection("scripts", required: false)

</body>
</html>