SourceCode/Management-Distributor/Management-Distributor/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Distributor.Dao._DbContext;
using Distributor.POCO;
using Distributor.Service.Interfaces;
using System.Text;

namespace Management_Distributor.Controllers
{
    //[AllowAnonymous]
    [Authorize(Roles = "Admin")]
    public class EmployeesController : Controller
    {
        IEmployeeService EmpService = null;
        IDeparmentService DeptService = null;
        public EmployeesController(IEmployeeService _EmpService, IDeparmentService _DeptService)
        {
            EmpService = _EmpService;
            DeptService = _DeptService;
        }




        // fetch 
        public JsonResult FetchEmployee(int PageNumber = 1)
        {
            
            var sbToreturn = new StringBuilder();
            List<Employee> employees = EmpService.Load_Page(PageNumber);
            return Json(new { data = employees }, JsonRequestBehavior.AllowGet);
        }

            //System.Threading.Thread.Sleep(3000);
            //for(int i=0;i< employees.Count();i++ )
            //{
            //    sbToreturn.AppendFormat(@"
            //                            <div class='card'>
            //                              < img src = '{0}' id='indicator' alt = 'Image no found' style = 'width:100%' >
            //                              < h1 > '{1}' </ h1 >
            //                              < p class='title'>'{2}'</p>
            //                              <p>'{3}'</p>
            //                              <div style = 'margin: 24px 0;' >
            //                                < a href= '#' >< i class='fa fa-dribbble'></i></a> 
            //                                <a href = '#' >< i class='fa fa-twitter'></i></a>  
            //                                <a href = '#' >< i class='fa fa-linkedin'></i></a>  
            //                                <a href = '#' >< i class='fa fa-facebook'></i></a> 
            //                             </div>
            //                             <p><button>'{4}'</button></p>
            //                            </div>
            //                           ", employees[i].AvatarUrl,
            //                              employees[i].EmpName,
            //                              employees[i].PhoneNumber,
            //                              employees[i].EmpAddress,
            //                               employees[i].EmpEmail);
            //}

            //return sbToreturn.ToString();
        //}

    // GET: Employees
    public ActionResult Index()
    {
        //var employees = EmpService.GetAll();
        return View();
    }

    // GET: Employees/Details/5
    public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = EmpService.GetOne(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(DeptService.GetAll(), "DepartmentId", "DepartmentName");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeId,EmpName,EmpAddress,PhoneNumber,EmpEmail,UserName,EncryptedPassword,Salt,LastLogged,NumOfLoginAttemp,LastAttemp,Role,DepartmentId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                EmpService.Add(employee);
                return RedirectToAction("Index");
            }

            ViewBag.DepartmentId = new SelectList(DeptService.GetAll(), "DepartmentId", "DepartmentName", employee.DepartmentId);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = EmpService.GetOne(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentId = new SelectList(DeptService.GetAll(), "DepartmentId", "DepartmentName", employee.DepartmentId);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeId,EmpName,EmpAddress,PhoneNumber,EmpEmail,UserName,EncryptedPassword,Salt,LastLogged,NumOfLoginAttemp,LastAttemp,Role,DepartmentId")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                EmpService.Edit(employee);
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentId = new SelectList(DeptService.GetAll(), "DepartmentId", "DepartmentName", employee.DepartmentId);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = EmpService.GetOne(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = EmpService.GetOne(id);
            EmpService.Delete(employee);
            return RedirectToAction("Index");
        }
    }
}

SourceCode/Management-Distributor/Management-Distributor/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Distributor.Dao._DbContext;
using Distributor.POCO;
using Distributor.Service.Interfaces;
using System.IO;
using Distributor.ViewModels;
using Pagination;

namespace Distributor.Controllers
{

    [Authorize(Roles = "staff")]
    public class ProductsController : Controller
    {
        private IProductService productService = null;
        private ICategoryService categoryService = null;

        public ProductsController(IProductService _productService, ICategoryService _categoryService)
        {
            productService = _productService;
            categoryService = _categoryService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Page(int page = 1)
        {
            List<Product> productz = productService.GetPage(page);
            ProductsListViewModel model = new ProductsListViewModel(){
                Products = productz,
                PagingInfo = new Pagination.PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = PageConfig.PageSize,
                    TotalItems = productService.GetAll().Count()
                }};

            return View(model);
        }

        public JsonResult LoadData(int categoryId)
        {
            var data = productService.GetByCategory(Convert.ToInt32(categoryId));
            return Json(new { data }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = productService.GetOne(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            List<Category> categories = categoryService.GetAll();
            ViewBag.CategoryId = new SelectList(categories, "CategoryId", "CategoryName");
            if (id == 0)
            {
                return View(new Product());
            }
            else
            {
                Product product = productService.GetOne(id);
                return View(product);
            }

        }

        [HttpPost]
        public ActionResult AddOrEdit(Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.ImageUrl != "")
                {
                    string fileName = Path.GetFileNameWithoutExtension(product.ImageUpload.FileName);
                    string extension = Path.GetExtension(product.ImageUpload.FileName);

                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    product.ImageUrl = "/Uploads/ProductImages/" + fileName;
                    product.ImageUpload.SaveAs(Path.Combine(Server.MapPath("/Uploads/ProductImages/"), fileName));
                }
                if (product.ProductId == 0)
                {
                    if (productService.Add(product))
                    {
                        return Json(new { success = true, message = "Add successfully" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { success = false, message = "Failed to add" }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {

                    if (productService.Edit(product))
                    {
                        return Json(new { success = true, message = "Edit successfully" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { success = false, message = "Failed to edit" }, JsonRequestBehavior.AllowGet);
                    }

                }
            }
            else return View();
            
        }

 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Remove(int id)
        {
            Product product = productService.GetOne(id);
            productService.Delete(product);
            return Json(new { success = true, message = "Removal success!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

SourceCode/Management-Distributor/Management-Distributor/Views/Employees/AddOrEdit.cshtml
@model Distributor.POCO.Product

@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Products", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ProductId)
    @Html.HiddenFor(model => model.ImageUrl)

    <input class="btn btn-file" type="file" name="ImageUpload" accept="image/jpeg, image/png" onchange="ShowImagePreview(this, document.getElementById('imagePreview'))" />
    <div style="width:200px;height:180px;margin: 10px auto;" class="text-center">
        <img class="img-fluid rounded" src="@Url.Content(Model.ImageUrl)" id="imagePreview" alt="Image Not Found" />
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label" })

        @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductName, new { @class = "control-label" })

        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })

        @Html.ValidationMessageFor(model => model.ProductName)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, new { @class = "control-label" })

        <div class="input-group">
            <span class="input-group-addon">$</span>
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        @Html.ValidationMessageFor(model => model.Price)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AvailableQty, new { @class = "control-label" })

        <div class="input-group">
            <span class="input-group-addon">$</span>
            @Html.EditorFor(model => model.AvailableQty, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        @Html.ValidationMessageFor(model => model.AvailableQty)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, new { @class = "control-label" })
        <div>
            <div class="input-group">
                @Html.TextAreaFor(model => model.Description, 2, 58, new { htmlAttributes = new { @class = "form-control", @id = "InputDescription" } })
            </div>
            @Html.ValidationMessageFor(model => model.Description)

        </div>


        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn btn-warning" />
    </div>
}

SourceCode/Management-Distributor/Management-Distributor/Views/Employees/Create.cshtml
@model Distributor.POCO.Employee

@{
    Layout = null;
}

@using (Html.BeginForm("Edit", "Employees", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "return SubmitForm(this)" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)

    <input class="btn btn-file" type="file" name="AvatarUpload" accept="image/jpeg, image/png" onchange="ShowImagePreview(this, document.getElementById('imagePreview'))" />
    <div style="width:200px;height:180px;margin: 10px auto;" class="text-center">
        <img class="img-fluid rounded" src="@Url.Content(Model.AvatarUrl)" id="imagePreview" alt="Image Not Found" />
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmpName, new { @class = "control-label" })

        @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control" } })

        @Html.ValidationMessageFor(model => model.EmpName)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmpAddress, new { @class = "control-label" })

        @Html.EditorFor(model => model.EmpAddress, new { htmlAttributes = new { @class = "form-control" } })

        @Html.ValidationMessageFor(model => model.EmpAddress)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.EncryptedPassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.EncryptedPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EncryptedPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label" })

        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })

        @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label" })

        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })

        @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmpEmail, new { @class = "control-label" })

        @Html.EditorFor(model => model.EmpEmail, new { htmlAttributes = new { @class = "form-control" } })

        @Html.ValidationMessageFor(model => model.EmpEmail)
    </div>
    <input type="submit" value="Submit" class="btn btn-primary" />
    <input type="reset" value="Reset" class="btn btn-warning" />
}

SourceCode/Management-Distributor/Management-Distributor/Views/Employees/Delete.cshtml
@model Distributor.POCO.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EncryptedPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EncryptedPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastLogged)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastLogged)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumOfLoginAttemp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumOfLoginAttemp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastAttemp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastAttemp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rolez)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rolez)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SourceCode/Management-Distributor/Management-Distributor/Views/Employees/Details.cshtml
@model Distributor.POCO.Employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Department.DepartmentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepartmentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EncryptedPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EncryptedPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastLogged)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastLogged)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumOfLoginAttemp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumOfLoginAttemp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastAttemp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastAttemp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rolez)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rolez)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EmployeeId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SourceCode/Management-Distributor/Management-Distributor/Views/Employees/Edit.cshtml
@model Distributor.POCO.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmployeeId)

        <div class="form-group">
            @Html.LabelFor(model => model.EmpName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EncryptedPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EncryptedPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EncryptedPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastLogged, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastLogged, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastLogged, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOfLoginAttemp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfLoginAttemp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfLoginAttemp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastAttemp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastAttemp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastAttemp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rolez, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rolez, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rolez, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "DepartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SourceCode/Management-Distributor/Management-Distributor/Views/Employees/Index.cshtml
@model IEnumerable<Distributor.POCO.Employee>

@{
	ViewBag.Title = "Dashboard | Employee";
}


<style>
	.avatar-Image {
		width: 200px;
		height: 200px;
	}

	body {
		padding-top: 30px;
	}

	.glyphicon {
		margin-bottom: 10px;
		margin-right: 10px;
	}

	small {
		display: block;
		line-height: 1.428571429;
		color: #999;
	}
</style>

<section class="tables">
	<div class="container-fluid">
		<div class="row" id="EmployDiv">

		</div>
	</div>
</section>

@section Scripts {
   <script>
	   $(document).ready(function(){

			CurrentPage = 1;

		   // Load First Page
		   LoadData(CurrentPage)

		   // Show more
		   $(window).scroll(function (){
		   if($(window).scrollTop() == $(document).height() - $(window).height())
		   {
				CurrentPage = CurrentPage + 1;
				LoadData(CurrentPage);
		   }
	   });


	   });
	   /*initial CurrentPage equal 1*/


	   function LoadData(currentPage) {
	   $.ajax({
			url: 'http://localhost:10193/Employees/FetchEmployee?pageNumber='+currentPage,
			type: "POST",
			success: function(data) { onSucess('#EmployDiv', data); }
	   });

}


function onSucess(element, data) {
	   var employeeTable = $(element);
	   $(data.data).each(function(index, emp){

			console.log(emp);
		   {
			   employeeTable.append(`
					<div class="col-lg-4">
				   <div class="well well-sm">
							<div class="row">
								<div class="lg-4 col-md-4 col-xs-6">
									<img src="/Uploads/ProfileImages/avatar-5.jpg" alt="" class="img-rounded img-fluid" />
								</div>
								<div class="lg-8 col-md-8 col-xs-6">
									<h4>
										${emp.EmpName}</h4>
									<small><cite title="San Francisco, USA">San Francisco, USA <i class="glyphicon glyphicon-map-marker">
									</i></cite></small>
									<p>
										<i class="glyphicon glyphicon-envelope"></i>${emp.EmpEmail}
										<br />
										<i class="glyphicon glyphicon-globe"></i><a href="http://www.jquery2dotnet.com">www.jquery2dotnet.com</a>
										<br />
										<i class="glyphicon glyphicon-gift"></i>June 02, 1988</p>
									<!-- Split button -->
									<div class="btn-group">
										<button type="button" class="btn btn-primary">
											Action</button>
										<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
											<span class="caret"></span><span class="sr-only">Action</span>
										</button>
										<ul class="dropdown-menu" role="menu">
											<li><a href="#">Edit</a></li>
											<li><a href="https://plus.google.com/+Jquery2dotnet/posts">Remove</a></li>
											<li class="divider"></li>
											<li><a href="#">Github</a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					 </div>
			`);
		   }
	   });
}
	</script>
	}