SourceCode/Management-Distributor/Management-Distributor/Controllers/DeliveryPlansController.cs
using Distributor.POCO;
using Distributor.Service.Interfaces;
using Distributor.ViewModels;
using Management_Distributor.Service.Interfaces;
using Pagination;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Management_Distributor.Controllers
{
    [Authorize]
    public class DeliveryPlansController : Controller
    {


        private IDeliveryPlanService deliveryPlanService = null;
        private IOrderService orderService = null;
        private IDistributorService distributorService = null;

        public DeliveryPlansController(IDeliveryPlanService _deliveryPlanService, IOrderService _orderService, IDistributorService _distributorService)
        {
            this.deliveryPlanService = _deliveryPlanService;
            this.orderService = _orderService;
        }
        // GET: DeliveryPlans
         public ActionResult Index()
        {
            return View();
        }
        // GET: Products

        // Page

        public ActionResult Page(int page = 1)
        {
            List<DeliveryPlan> productz = deliveryPlanService.GetPage(page);
            DeliveryPlansListViewModel model = new DeliveryPlansListViewModel()
            {
                DeliveryPlans = productz,
                PagingInfo = new Pagination.PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = PageConfig.PageSize,
                    TotalItems = deliveryPlanService.GetAll().Count()
                }

            };
            return View(model);
        }
        public JsonResult LoadData(int deliveryPlanId)
        {
            //var data = db.Categories.ToList();
            var data = deliveryPlanService.GetAll();
            return Json(new { data }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {

            List<Order> orders = orderService.GetAll();
            ViewBag.OrderId = new SelectList(orders, "OrderID", "OrderId");

            if (id == 0)
            {
                return View(new DeliveryPlan());
            }
            else
            {
                DeliveryPlan deliveryPlan = deliveryPlanService.GetOne(id);
                return View(deliveryPlan);
            }

        }

        [HttpPost]
        public ActionResult AddOrEdit(DeliveryPlan deliveryPlan)
        {

            if (deliveryPlan.DeliveryPlanId == 0)
            {
                if (deliveryPlanService.Add(deliveryPlan))
                {
                    return Json(new { success = true, message = "Add successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = "Failed to add" }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {

                if (deliveryPlanService.Edit(deliveryPlan))
                {
                    return Json(new { success = true, message = "Edit successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = "Failed to edit" }, JsonRequestBehavior.AllowGet);
                }

            }
        }

        // GET: Products/Details/5
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryPlan deliveryPlan = deliveryPlanService.GetOne(id);
            if (deliveryPlan == null)
            {
                return HttpNotFound();
            }
            return View(deliveryPlan);
        }
        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ProductId,ProductName,Price,Description,CategoryId")] DeliveryPlan deliveryPlan)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        deliveryPlanService.Add(deliveryPlan);
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.CategoryId = new SelectList(CategoriesForSelectList(), "CategoryId", "CategoryName", deliveryPlan.CategoryId);
        //    return View(deliveryPlan);
        //}

        // GET: Products/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    if (id == 0)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    DeliveryPlan deliveryPlan = deliveryPlanService.GetOne(id);
        //    if (deliveryPlan == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.CategoryId = new SelectList(CategoriesForSelectList(), "CategoryId", "CategoryName", deliveryPlan.CategoryId);
        //    return View(deliveryPlan);
        //}

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ProductId,ProductName,Price,Description,CategoryId")] DeliveryPlan deliveryPlan)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        deliveryPlanService.Edit(deliveryPlan);
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.CategoryId = new SelectList(CategoriesForSelectList(), "CategoryId", "CategoryName", deliveryPlan.CategoryId);
        //    return View(deliveryPlan);
        //}

        // GET: Products/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryPlan deliveryPlan = deliveryPlanService.GetOne(id);
            if (deliveryPlan == null)
            {
                return HttpNotFound();
            }
            return View(deliveryPlan);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DeliveryPlan deliveryPlan = deliveryPlanService.GetOne(id);
            deliveryPlanService.Delete(deliveryPlan);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Remove(int id)
        {
            DeliveryPlan deliveryPlan = deliveryPlanService.GetOne(id);
            deliveryPlanService.Delete(deliveryPlan);
            return Json(new { success = true, message = "Removal success!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

SourceCode/Management-Distributor/Management-Distributor/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Distributor.Dao._DbContext;
using Distributor.POCO;
using Distributor.Service.Interfaces;

namespace Distributor.Controllers
{
    //[AllowAnonymous]
    //[Authorize]

    [Authorize(Roles = "Admin")]
    public class DepartmentsController : Controller
    {
        IEmployeeService EmpService = null;
        IDeparmentService DeptService = null;

        public DepartmentsController(IEmployeeService _EmpService, IDeparmentService _DeptService)
        {
            EmpService = _EmpService;
            DeptService = _DeptService;
        }
        //[Authorize(Roles = "V,A")]
        public ActionResult Index()
        {
            var departments = DeptService.GetAll();
            return View(departments);
        }

        // GET: Departments/Details/5
        public ActionResult Details(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = DeptService.GetOne(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        //[Authorize(Roles = "A")]
        // GET: Departments/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeEmployeeId = new SelectList(EmpService.GetAll(), "EmployeeId", "EmpName");
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentId,DepartmentName,EmployeeId")] Department department)
        {
            if (ModelState.IsValid)
            {
                DeptService.Add(department);
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeEmployeeId = new SelectList(EmpService.GetAll(), "EmployeeId", "EmpName", department.EmployeeId);
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = DeptService.GetOne(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeEmployeeId = new SelectList(EmpService.GetAll(), "EmployeeId", "EmpName", department.EmployeeId);
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult  Edit([Bind(Include = "DepartmentId,DepartmentName,EmployeeId")] Department department)
        {
            if (ModelState.IsValid)
            {
                DeptService.Edit(department);
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeEmployeeId = new SelectList(EmpService.GetAll(), "EmployeeId", "EmpName", department.EmployeeId);
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = DeptService.GetOne(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = DeptService.GetOne(id);
            return RedirectToAction("Index");
        }
    }
}

SourceCode/Management-Distributor/Management-Distributor/Views/DeliveryPlans/AddOrEdit.cshtml
@model Distributor.POCO.DeliveryPlan

@{
    Layout = null;
}
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<link href="~/Content/jquery.datetimepicker.css" rel="stylesheet" />
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/jquery.datetimepicker.js"></script>
<script src="~/Content/"></script>
<script>
        $(document).ready(function () {
            $('#DeliveryDate').datepicker({
                minDate: new Date(),
                defaultDate: '@Model.DeliveryDate',
            });
        });

</script>

<input type="text" name="name" class="datetimepicker" value="" />

@using (Html.BeginForm("AddOrEdit", "DeliveryPlans", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.DeliveryPlanId)

    <div class="form-group">
        @Html.LabelFor(model => model.OrderId, "OrderId", htmlAttributes: new { @class = "control-label" })

        @Html.DropDownList("OrderId", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DeliveryDate, new { @class = "control-label", @Value = Model.DeliveryDate.ToString("MM/dd/yyyy"), })

        @Html.TextBoxFor(model => model.DeliveryDate, new { htmlAttributes = new { @class = "form-control datetimepicker"} })

        @Html.ValidationMessageFor(model => model.DeliveryDate)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, new { @class = "control-label" })
        <div>
            <div class="input-group">
                @Html.TextAreaFor(model => model.Description, 2, 80, new { htmlAttributes = new { @class = "form-control", @id = "InputDescription" } })
            </div>
            @Html.ValidationMessageFor(model => model.Description)

        </div>


        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn btn-warning" />
    </div>
}

SourceCode/Management-Distributor/Management-Distributor/Views/DeliveryPlans/Page.cshtml
@model Distributor.ViewModels.DeliveryPlansListViewModel
@{
    ViewBag.Title = "Page";
}

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@


<style>
    /*.ui-widget-overlay {
        z-index: 0;
    }*/

    /*.ui-dialog {
        z-index: 9999 !important;
    }*/

    .ui-widget-overlay {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }
</style>

<!-- Page Header-->
<header style="margin-top: 0;" class="page-header">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Products</h2>
    </div>
</header>
<section style="padding: 10px 0;" class="tables">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center">
                        <h3 class="h4"><a class="btn" style="background-color:#36d2a5;color:#fff;" onclick="PopupForm('@Url.Action("AddOrEdit","DeliveryPlans")')"><i class="fa fa-plus-circle">  Add New</i></a></h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-hover text-center">
                            <thead>
                                <tr>
                                    <th>DeliveryDate</th>
                                    <th>Description</th>
                                    <th>Status</th>
                                    <th>OrderId</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var p in Model.DeliveryPlans)
                                {

                                    RenderPartialExtensions.RenderPartial(Html, "_DeliveryPlan", p);

                                }
                            </tbody>
                        </table>
                        <div class="btn-group pull-right">
                            @Html.PageLinks(Model.PagingInfo, x => Url.Action("Page", new { page = x }))
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @*<script>
            $(document).ready(function () {
                $('#datetimepicker').datepicker({
                    minDate: new Date()
                });
            });

        </script>*@

    <script src="~/Scripts/ProductAddition.js"></script>

    @*<script src="~/Scripts/jquery.datetimepicker.js"></script>*@
    <script>
        $(document).ready(function () {
            $('#DeliveryDate').datepicker({
                minDate: new Date(),
                @*defaultDate: '@Model.DeliveryDate',*@
            });
        });

    </script>
    <script>
        var Popup;

        /* Show add/edit Form */
        function PopupForm(url)
        {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response)
                Popup = formDiv.dialog({
                    autoOpen: true,
                    resizable: false,

                    title: 'Add/Update DeliveryPlan',
                    height: 800,
                    width: 700,
                    close: function()
                    {
                        Popup.dialog('destroy')
                            .remove();
                    }
                });
            });
        }
        /* End Show add/edit Form */

        /* Submit add/Edit Form*/
        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {

                var ajaxConfig = {
                    async: true,
                    type: "POST",
                    url: form.action,
                    data: new FormData(form),
                    success: function (data) {
                        if (data.success == true) {
                            Popup.dialog('close');
                            /*Refetch :))*/
                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            });
                        }
                        else {
                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "Error"
                            });
                        }
                    }
                }


                if ($(form).attr('enctype') == "mutilpart/form-data") {
                    ajaxConfig["contenType"] = false;
                    ajaxConfig["processData"] = false;
                }

                $.ajax(ajaxConfig);
            }
            return false;
        }
        /* End Submit add/Edit Form*/

        /* Remove record opt */

        function Delete(id) {
            if(confirm('Are you Sure to remove this product record ?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Remove", "DeliveryPlans")/' + id,
                    success: function (data) {
                        if (data.success) {
                           /*Refetch :))*/

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            });

                        }
                        else {
                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "Error"
                            });
                        }
                    }
                });
            }
        }

        /* End Remove record opt */


        //

    </script>
}

SourceCode/Management-Distributor/Management-Distributor/Views/DeliveryPlans/_DeliveryPlan.cshtml
@model Distributor.POCO.DeliveryPlan

<style>
    .product-Image {
        height: 100px;
        width: 100px;
    }
</style>

<tr>
    <td>@Html.DisplayFor(ModelItem => Model.DeliveryDate)</td>
    <td>@Html.DisplayFor(ModelItem => Model.Description)</td>
    <td>@Html.DisplayFor(ModelItem => Model.Status)</td>
    <td>@Html.DisplayFor(ModelItem => Model.OrderId)</td>
    @*<td width="15%">@Html.DisplayFor(ModelItem => Model.Price)</td>*@
    <td>
        @*<a href="@Url.Action("Edit", "Departments")">
                <i class="fa fa-edit"></i>
                Edit |
            </a>*@

        <a class='btn btn-success btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","DeliveryPlans")/@Model.DeliveryPlanId')><i class='fa fa-pencil-square-o' aria-hidden='true'></i></a>

        <a class='btn btn-danger btn-sm' onclick=Delete('@Model.DeliveryPlanId')><i class='fa fa-trash' aria-hidden='true'></i></a>
    </td>
    @*@Html.ActionLink("Edit", "Edit", new { id = p.ProductId }) |
        @Html.ActionLink("Details", "Details", new { id = p.ProductId }) |
        @Html.ActionLink("Delete", "Delete", new { id = p.ProductId })*@

</tr>